### ISSUE TITLE
[Bug] Unresponsive after a while

### ISSUE THREAD

**Issue by pabloes** [decentraland/marketplace#228]
After few seconds, an error appears in console and then the app becomes blocked in content and selection, error shown in console is:
```uncaught at S at S 
 at S 
 at  
 at T 
 at O 
 TypeError: c.delay is not a function
    at https://land.decentraland.org/static/js/main.384caa07.js:1:2726009
    at https://land.decentraland.org/static/js/main.384caa07.js:1:2721798
    at Object.next (https://land.decentraland.org/static/js/main.384caa07.js:1:2721903)
    at M (https://land.decentraland.org/static/js/main.384caa07.js:1:721269)
    at _ (https://land.decentraland.org/static/js/main.384caa07.js:1:722106)
```

To reproduce, just wait , and error appears in console, then the app is blocked.

**Comment by nachomazzara** [comment]
Closing this cause we can not reproduce it
